config/routes.rb
Tokkenz::Application.routes.draw do

  resources :stores
  resources :stars
  resources :series
  resources :characters
  resources :packs
  resources :tokens
  resources :trades do
    get 'search', :on => :collection
    get 'cancel', :on => :member
  end
  resources :bids do
    get 'trade_bids', :on => :collection
    get 'accept', :on => :member
    get 'cancel', :on => :member
  end
  resources :players do
    get 'login', :on => :collection
    get 'signup', :on => :collection
    get 'signup', :on => :member
    get 'favorites', :on => :member
  end
  resources :sessions, :only => [:new, :create, :destroy]

  match '/home', :to => 'home#welcome'
  match '/contact', :to => 'main#contact'
  match '/about', :to => 'main#about'
  match '/help', :to => 'main#help'
  match '/jobs', :to => 'main#jobs'
  match '/whats_new', :to => 'main#whats_new'
  match 'search', :to => 'main#search'
  match '/signup', :to => 'players#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  root :to => "main#welcome"

end

app/controllers/main_controller.rb
class MainController < ApplicationController

  def welcome
    @title = "Home"
  end

  def home
    @title = "Home"
  end

  def contact
    @title = "Contact"
  end

  def about
    @title = "About"
  end

  def help
    @title = "Help"
  end

  def jobs
    @title = "Help"
  end

  def search
    @all_series = Series.all
    @series = []
    upcase_search_string = params[:search_string].upcase
    @all_series.each do |s|
      if s.name.upcase.include?(upcase_search_string)
        @series << s
      end
    end
    #@series.paginate( :page => params[:page] )
  end

  def whats_new
    @title = "what\'s new?"
    @series = Series.paginate( :page => params[:page] )
  end

end

app/views/main/_series_order_list.html.erb
<li>
  <%= link_to series.name, series %>
  <% if current_player %>
    | <%= link_to "add to cart", series, :controller => :cart_items, :method => :create %>
  <% end %>
  <% if current_player && current_player.admin? %>
    | <%= link_to "delete", series, :method => :delete, :confirm => "You sure?",
                                :title => "Delete #{series.name}" %>
  <% end %>
</li>

app/views/main/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/main/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/main/error.html.erb
<%= @page_title = "Error" %>
<%= @message %>

app/views/main/help.html.erb
<h1>Help</h1>
<p>
  Get help on Ruby on Rails Tutorial at the
  <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
</p>

app/views/main/home.html.erb
<p>
  This is the home page for tokkenz.
</p>

<%= link_to "sign up now", signup_path %> or <%= link_to "sign in", signin_path %>

app/views/main/jobs.html.erb
<h1>Help</h1>
<p>
  Get help on Ruby on Rails Tutorial at the
  <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
</p>

app/views/main/search.html.erb
<h1>search results</h1>


<ul class="series">
  <% @series.each do |s| %>
    <li><%= s.name %>
  <% end %>
</ul>

app/views/main/welcome.html.erb
<h1>welcome to tokkenz!</h1>
<hr />
<% if signed_in? %>
  <h3>welcome, <%= current_player.first_name %> </h3>
<% else %>
  <p>check out today's featured tokkenz!</p>
  <p><%= link_to "what's new?", whats_new_path %></p>
  <br />
  <p><%= link_to "sign up now", signup_path %> to start collecting and find friends!
  <br /> or
  <br />
  <%= link_to "sign in", signin_path %> to find new tokkenz or trade for new ones!</p>
<% end %>

app/views/main/whats_new.html.erb
<p>
  what's new?
<%= will_paginate @series %>

<ul class="series">
<% @series.each do |s| %>
<li>
  <%= link_to s.name, s %>
  <% if signed_in? %>
    | <%= link_to "add to cart", s %>
  <% end %>
  <% if admin_player? %>
    | <%= link_to "delete", s, :method => :delete, :confirm => "Are you sure?",
                                :title => "Delete #{s.name}" %>
  <% end %>
</li>
<% end %>
</ul>

<%= will_paginate @series %>
</p>