config/routes.rb
Tokkenz::Application.routes.draw do

  resources :stores
  resources :stars
  resources :series
  resources :characters
  resources :packs
  resources :tokens
  resources :trades do
    get 'search', :on => :collection
    get 'cancel', :on => :member
  end
  resources :bids do
    get 'trade_bids', :on => :collection
    get 'accept', :on => :member
    get 'cancel', :on => :member
  end
  resources :players do
    get 'login', :on => :collection
    get 'signup', :on => :collection
    get 'signup', :on => :member
    get 'favorites', :on => :member
  end
  resources :sessions, :only => [:new, :create, :destroy]

  match '/home', :to => 'home#welcome'
  match '/contact', :to => 'main#contact'
  match '/about', :to => 'main#about'
  match '/help', :to => 'main#help'
  match '/jobs', :to => 'main#jobs'
  match '/whats_new', :to => 'main#whats_new'
  match 'search', :to => 'main#search'
  match '/signup', :to => 'players#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  root :to => "main#welcome"

end

app/models/token.rb
class Token < ActiveRecord::Base

  belongs_to :player
  belongs_to :character
  belongs_to :trades_tokens

end

app/controllers/tokens_controller.rb
class TokensController < ApplicationController

  include SessionsHelper

  before_filter :authenticate
  #before_filter :admin_player, :except => [ :create, :show, :index ]

  #def new
  #  @token = token.new
  #  @title = "add new token"
  #end

  def create
    #
    # Fix this -- we need to create series.tokens_per_pack tokens
    # with random characters from the series.
    #
    @pack = Pack.find(params[:pack_id])
    @pack.series.tokens_per_pack.times do
      @token = Token.create!( :player_id => current_player.id,
                              :character_id => 1 )
    end
    flash.now[:success] = "pack opened"
    @pack.destroy
    #@tokens = Token.where( :player_id => current_player.id ).paginate( :page => params[:page] )
    @tokens = current_player.tokens.paginate( :page => params[:page] )
    render 'index'
  end

  def index
    @title = "list tokens"
    @tokens = current_player.tokens.paginate( :page => params[:page] )
    #@tokens = Token.where( :player_id => current_player.id ).paginate( :page => params[:page] )
  end

  def show
    @token = Token.find(params[:id])
  end

  #def edit
  #  @token = token.find(params[:id])
  #  @title = "edit token"
  #end

  #def update
  #  @token = token.find(params[:id])
  #  if @token.update_attributes(params[:token])
  #    flash[:success] = "#{@token.name} was successfully updated."
  #    redirect_to @token
  #  else
  #    @title = "edit token"
  #    render 'edit'
  #  end
  #end

  def destroy
    Token.find(params[:id]).destroy
    flash[:success] = "token deleted."
    redirect_to token_path
  end

end

app/views/tokens/_form.html.erb
<%= form_for(@star) do |f| %>
  <% if @star.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@star.errors.count, "error") %> prohibited this star from being saved:</h2>

      <ul>
      <% @star.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tokens/_token.html.erb
<li>
  <%= link_to token.character.name, token %>,
  <%= token.character.id %>, <%= token.id %>
  | <%= link_to 'trade!', new_trade_path(:token_id => token.id) %>
  <% if admin_player? %>
    | <%= link_to "delete", token, :method => :delete, :confirm => "You sure?",
                                :title => "Delete #{token.id.to_s}" %>
  <% end %>
</li>

app/views/tokens/_token_fields_form.html.erb
<%= form_for(@token) do |f| %>
 <%= render 'shared/error_messages', :object => f.object %>
 <div class="field">
    <%= f.label :name, "Name" %><br />
    <%= f.text_field :name %>
  </div>
 <div class="field">
    <%= f.label :image, "Image" %><br />
    <%= f.text_field :image %>
  </div>
 <div class="field">
    <%= f.label :description, "Description" %><br />
    <%= f.text_area :description, :rows => 10 %>
  </div>
  <div class="field">
    <%= f.label :tokens_per_pack, "Tokens per pack" %><br />
    <%= f.text_field :tokens_per_pack %>
  </div>
  <div class="field">
    <%= f.label :packs_minted, "Packs minted" %><br />
    <%= f.text_field :packs_minted %>
  </div>
  <div class="field">
    <%= f.label :packs_issued, "Packs issued" %><br />
    <%= f.text_field :packs_issued %>
  </div>
  <div class="field">
    <%= f.label :release_date, "Release date" %><br />
    <%= f.text_field :release_date %>
  </div>
  <div class="field">
    <%= f.label :term_date, "Term date" %><br />
    <%= f.text_field :term_date %>
  </div>
  <div class="actions">
    <%= f.submit "submit" %>
  </div>
<% end %>

app/views/tokens/edit.html.erb
<h1>Editing series</h1>

<%= render 'series_fields_form' %>

<%= link_to 'show this series', @series %> |
<%= link_to 'list available series', series_index_path %>

app/views/tokens/index.html.erb
<h1>my tokens</h1>

<%= will_paginate %>

<ul class="tokens">
  <%= render @tokens %>
</ul>

<%= will_paginate %>

app/views/tokens/new.html.erb
<h1>New series</h1>
<%= render 'series_fields_form' %>

<%= link_to 'available series', series_index_path %>

app/views/tokens/show.html.erb
<p id="notice"><%= notice %></p>
<h1>token detail</h1>
<p><br />
<p>Token name: <%= @token.character.name %>
<br />Series name: <%= @token.character.series.name %>
<br />Token ID: <%= @token.id %>
<br />Series ID: <%= @token.character.series.id %>
<br />Character ID: <%= @token.character_id %>
<br />Image: <%= @token.character.image %>
<br />Desc: <%= @token.character.description %>
<br />Release date: <%= @token.character.series.release_date %>
<br /><br />

<%= link_to 'trade!', trades_path(:token_id => @token), :method => :post %>
</p>