config/routes.rb
Tokkenz::Application.routes.draw do

  resources :stores
  resources :stars
  resources :series
  resources :characters
  resources :packs
  resources :tokens
  resources :trades do
    get 'search', :on => :collection
    get 'cancel', :on => :member
  end
  resources :bids do
    get 'trade_bids', :on => :collection
    get 'accept', :on => :member
    get 'cancel', :on => :member
  end
  resources :players do
    get 'login', :on => :collection
    get 'signup', :on => :collection
    get 'signup', :on => :member
    get 'favorites', :on => :member
  end
  resources :sessions, :only => [:new, :create, :destroy]

  match '/home', :to => 'home#welcome'
  match '/contact', :to => 'main#contact'
  match '/about', :to => 'main#about'
  match '/help', :to => 'main#help'
  match '/jobs', :to => 'main#jobs'
  match '/whats_new', :to => 'main#whats_new'
  match 'search', :to => 'main#search'
  match '/signup', :to => 'players#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  root :to => "main#welcome"

end

app/models/character.rb
class Character < ActiveRecord::Base
  belongs_to :series
  belongs_to :star
  has_many   :tokens
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController

  include SessionsHelper

  before_filter :authenticate, :except => [ :show, :index ]
  before_filter :admin_player, :except => [ :show, :index ]

  def new
    @character = Character.new
    @title = "add new character"
  end

  def create
    @character = Character.new(params[:character])
    if @character.save
      flash.now[:success] = "#{@character.name} added."
      redirect_to @character
    else
      @title = 'add new character'
      render 'new'
    end
  end

  def index
    @title = "list characters"
    @characters = Character.paginate( :page => params[:page] )
  end

  def show
    @character = Character.find(params[:id])
  end

  def edit
    @character = Character.find(params[:id])
    @title = "edit character"
  end

  def update
    @character = Character.find(params[:id])
    if @character.update_attributes(params[:Character])
      flash[:success] = "#{@character.name} was successfully updated."
      redirect_to @character
    else
      @title = "edit character"
      render 'edit'
    end
  end

  def destroy
    Character.find(params[:id]).destroy
    flash[:success] = "character deleted."
    redirect_to character_path
  end

end

app/views/characters/_character.html.erb
<li>
  <%= link_to character.name, character %>
  <% if current_player && current_player.admin? %>
    | <%= link_to "delete", character, :method => :delete, :confirm => "You sure?",
                                :title => "Delete #{character.name}" %>
  <% end %>
</li>

app/views/characters/_character_fields_form.html.erb
<%= form_for(@character) do |f| %>
 <%= render 'shared/error_messages', :object => f.object %>
 <div class="field">
    <%= f.label :name, "Name" %><br />
    <%= f.text_field :name %>
  </div>
 <div class="field">
    <%= f.label :image, "Image" %><br />
    <%= f.text_field :image %>
  </div>
 <div class="field">
    <%= f.label :description, "Description" %><br />
    <%= f.text_area :description, :rows => 10 %>
  </div>
  <div class="field">
    <%= f.label :quantity, "Quantity" %><br />
    <%= f.text_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :series_id, "Series ID" %><br />
    <%= f.text_field :series_id %>
  </div>
  <div class="field">
    <%= f.label :star_id, "Star ID" %><br />
    <%= f.text_field :star_id %>
  </div>
  <div class="actions">
    <%= f.submit "submit" %>
  </div>
<% end %>

app/views/characters/_form.html.erb
<%= form_for(@star) do |f| %>
  <% if @star.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@star.errors.count, "error") %> prohibited this star from being saved:</h2>

      <ul>
      <% @star.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/characters/edit.html.erb
<h1>editing character</h1>

<%= render 'character_fields_form' %>

<%= link_to 'Show', @character %> |
<%= link_to 'Back', characters_path %>

app/views/characters/index.html.erb
<h1>Listing characters</h1>

<%= will_paginate %>

<ul class="characters">
  <%= render @characters %>
</ul>

<%= will_paginate %>


<% if admin_player? %>
<%= link_to 'create new character', new_character_path %>
<% end %>

app/views/characters/new.html.erb
<h1>New character</h1>
<%= render 'character_fields_form' %>

<%= link_to 'Back', characters_path %>

app/views/characters/show.html.erb
<p id="notice"><%= notice %></p>
Name, ID: <%= @character.name %>, <%= @character.id %>
<br />Image: <%= @character.image %>
<br />Desc:  <%= @character.description %>
<br />Qty:   <%= number_with_delimiter @character.quantity %>
<br />Series: <%= @character.series_id %>
<br />Star: <%= @character.star_id %>
<br /><br />
<% if admin_player? %>
<%= link_to 'edit this character', edit_character_path(@character) %> |
<% end %>
<%= link_to 'list characters', characters_path %>