config/routes.rb
Tokkenz::Application.routes.draw do

  resources :stores
  resources :stars
  resources :series
  resources :characters
  resources :packs
  resources :tokens
  resources :trades do
    get 'search', :on => :collection
    get 'cancel', :on => :member
  end
  resources :bids do
    get 'trade_bids', :on => :collection
    get 'accept', :on => :member
    get 'cancel', :on => :member
  end
  resources :players do
    get 'login', :on => :collection
    get 'signup', :on => :collection
    get 'signup', :on => :member
    get 'favorites', :on => :member
  end
  resources :sessions, :only => [:new, :create, :destroy]

  match '/home', :to => 'home#welcome'
  match '/contact', :to => 'main#contact'
  match '/about', :to => 'main#about'
  match '/help', :to => 'main#help'
  match '/jobs', :to => 'main#jobs'
  match '/whats_new', :to => 'main#whats_new'
  match 'search', :to => 'main#search'
  match '/signup', :to => 'players#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  root :to => "main#welcome"

end

app/controllers/series_controller.rb
class SeriesController < ApplicationController

  include SessionsHelper

  before_filter :authenticate, :except => [ :show, :index ]
  before_filter :admin_player, :except => [ :show, :index ]

  def new
    @series = Series.new
    @title = "add new series"
  end

  def create
    @series = Series.new(params[:series])
    if @series.save
      flash.now[:success] = "#{@series.name} added."
      redirect_to @series
    else
      @title = 'add new series'
      render 'new'
    end
  end

  def index
    @title = "list series"
    @series = Series.where( "packs_minted > packs_issued" ).paginate( :page => params[:page] )
  end

  def show
    @series = Series.find(params[:id])
  end

  def edit
    @series = Series.find(params[:id])
    @title = "edit series"
  end

  def update
    @series = Series.find(params[:id])
    if @series.update_attributes(params[:series])
      flash[:success] = "#{@series.name} was successfully updated."
      redirect_to @series
    else
      @title = "edit series"
      render 'edit'
    end
  end

  def destroy
    Series.find(params[:id]).destroy
    flash[:success] = "series deleted."
    redirect_to series_path
  end

end

app/views/series/_form.html.erb
<%= form_for(@star) do |f| %>
  <% if @star.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@star.errors.count, "error") %> prohibited this star from being saved:</h2>

      <ul>
      <% @star.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/series/_series.html.erb
<li>
  <%= link_to series.name, series %>
  <% if admin_player? %>
    | <%= link_to "delete", series, :method => :delete, :confirm => "You sure?",
                                :title => "Delete #{series.name}" %>
  <% end %>
</li>

app/views/series/_series_fields_form.html.erb
<%= form_for(@series) do |f| %>
 <%= render 'shared/error_messages', :object => f.object %>
 <div class="field">
    <%= f.label :name, "Name" %><br />
    <%= f.text_field :name %>
  </div>
 <div class="field">
    <%= f.label :image, "Image" %><br />
    <%= f.text_field :image %>
  </div>
 <div class="field">
    <%= f.label :description, "Description" %><br />
    <%= f.text_area :description, :rows => 10 %>
  </div>
  <div class="field">
    <%= f.label :tokens_per_pack, "Tokens per pack" %><br />
    <%= f.text_field :tokens_per_pack %>
  </div>
  <div class="field">
    <%= f.label :packs_minted, "Packs minted" %><br />
    <%= f.text_field :packs_minted %>
  </div>
  <div class="field">
    <%= f.label :packs_issued, "Packs issued" %><br />
    <%= f.text_field :packs_issued %>
  </div>
  <div class="field">
    <%= f.label :release_date, "Release date" %><br />
    <%= f.text_field :release_date %>
  </div>
  <div class="field">
    <%= f.label :term_date, "Term date" %><br />
    <%= f.text_field :term_date %>
  </div>
  <div class="actions">
    <%= f.submit "submit" %>
  </div>
<% end %>

app/views/series/edit.html.erb
<h1>Editing series</h1>

<%= render 'series_fields_form' %>

<%= link_to 'show this series', @series %> |
<%= link_to 'list available series', series_index_path %>

app/views/series/index.html.erb
<h1>Listing series</h1>

<%= will_paginate %>

<ul class="series">
  <%= render @series %>
</ul>

<%= will_paginate %>


<% if admin_player? %>
<%= link_to 'create new series', new_series_path %>
<% end %>

app/views/series/new.html.erb
<h1>New series</h1>
<%= render 'series_fields_form' %>

<%= link_to 'available series', series_index_path %>

app/views/series/show.html.erb
<p id="notice"><%= notice %></p>
<h1>pack detail</h1>
<br />
<p>Name, ID: <%= @series.name %>, <%= @series.id %>
<br />Image: <%= @series.image %>
<br />Desc: <%= @series.description %>
<br />Tokens/pack: <%= number_with_delimiter @series.tokens_per_pack %>
<br />Packs minted: <%= number_with_delimiter @series.packs_minted %>
<br />Packs issued: <%= number_with_delimiter @series.packs_issued %>
<br />Release date: <%= @series.release_date %>
<br /><br />

<% if signed_in? and !admin_player? %>
  <%= link_to 'buy now', packs_path(:series_id => @series), :method => :post %>
<% end %>

<% if admin_player? %>
  <%= link_to 'edit this series', edit_series_path(@series) %> |
<% end %>
</p>